environment: minikube
serviceAccount: spark-spark
imageRegistry: localhost:5000
arguments:
  - "/tmp/data-in/"
  - "/tmp/data-out/"
volumes:
  - name: input-data
    hostPath:
      path: /tmp/data-in/
  - name: output-data
    hostPath:
      path: /tmp/data-out/
mounts:
  input-data: /tmp/data-in/
  output-data: /tmp/data-out/
driver:
  volumeMounts:
    - name: input-data
      mountPath: /tmp/data-in/
    - name: output-data
      mountPath: /tmp/data-out/
  cores: 1
  memory: "2g"
executor:
  volumeMounts:
    - name: input-data
      mountPath: /tmp/data-in/
    - name: output-data
      mountPath: /tmp/data-out/
  instances: 2
  cores: 1
  memory: "1g"
hadoopConf:
sparkConf:
hostNetwork: false
imagePullPolicy: Never
userId: 0
